// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byzwcocakjoqepewdvgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5endjb2Nha2pvcWVwZXdkdmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNTIzNDUsImV4cCI6MjA3NjkyODM0NX0.5IKmBpN9_s6Bk61Wtp42cNaQJM82HA5T_NNQafGPs08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});